version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: animefav_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - animefav_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 10s
      retries: 5
      interval: 10s

  redis:
    image: redis:7-alpine
    container_name: animefav_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - animefav_network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
     build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: animefav_backend
    restart: unless-stopped
    ports:
      - "3001:3000"
    environment:
      PORT: 3000
      DB_HOST: db
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_NAME: ${DB_NAME}
      DATABASE_URL: mysql://${DB_USER}:${DB_PASS}@db:3306/${DB_NAME}   # <-- nuevo, lo usa Prisma
      JWT_SECRET: ${JWT_SECRET}
      REDIS_HOST: redis
      REDIS_PORT: 6379
      RESEND_API_KEY: ${RESEND_API_KEY}
      CLOUDINARY_CLOUD_NAME: ${CLOUDINARY_CLOUD_NAME}
      CLOUDINARY_API_KEY: ${CLOUDINARY_API_KEY}
      CLOUDINARY_API_SECRET: ${CLOUDINARY_API_SECRET}
      NODE_ENV: production
    entrypoint: ["/bin/sh", "entrypoint.sh"]   # <-- nuevo
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - animefav_network

volumes:
  db_data:
  redis_data:

networks:
  animefav_network:
    driver: bridge
    